// Copyright (c) 2015 Alcatel-Lucent, (c) 2016 Nokia
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the copyright holder nor the names of its contributors
//       may be used to endorse or promote products derived from this software without
//       specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


extern crate serde;
#[macro_use]
extern crate serde_derive;
extern crate serde_json;
extern crate bambou;
extern crate reqwest;


mod containerinterface;
mod groupkeyencryptionprofile;
mod brconnection;
mod qos;
mod ingressadvfwdentrytemplate;
mod bgppeer;
mod sharednetworkresource;
mod virtualip;
mod pspatmap;
mod via;
mod multicastchannelmap;
mod redundancygroup;
mod tca;
mod group;
mod autodiscoveredgateway;
mod zone;
mod ikegatewayprofile;
mod ikesubnet;
mod infrastructuregatewayprofile;
mod diskstat;
mod flowsecuritypolicy;
mod vcentereamconfig;
mod routingpolicy;
mod enterprisesecurity;
mod vcentervrsconfig;
mod ducgroup;
mod nexthop;
mod enterprisenetwork;
mod infrastructurevscprofile;
mod permission;
mod ipreservation;
mod redirectiontargettemplate;
mod subnettemplate;
mod floatingipacltemplate;
mod ikegatewayconnection;
mod redirectiontarget;
mod firewallacl;
mod patipentry;
mod aggregatemetadata;
mod networklayout;
mod ingressexternalservicetemplateentry;
mod dscpforwardingclasstable;
mod avatar;
mod overlayaddresspool;
mod bootstrapactivation;
mod licensestatus;
mod lteinformation;
mod cloudmgmtsystem;
mod vsp;
mod domain;
mod eventlog;
mod redundantport;
mod dscpforwardingclassmapping;
mod porttemplate;
mod overlaypatnatentry;
mod vsc;
mod vsd;
mod zfbautoassignment;
mod vport;
mod flowforwardingpolicy;
mod port;
mod statisticspolicy;
mod subnet;
mod container;
mod ratelimiter;
mod keyservermonitorencryptedseed;
mod gatewaytemplate;
mod uplinkrd;
mod keyservermonitorseed;
mod metadata;
mod vrs;
mod hsc;
mod vlan;
mod ldapconfiguration;
mod vsdcomponent;
mod zfbrequest;
mod enterprisepermission;
mod staticroute;
mod connectionendpoint;
mod job;
mod vminterface;
mod gatewaysecureddata;
mod vcenterhypervisor;
mod ptranslationmap;
mod keyservermonitor;
mod ducgroupbinding;
mod vrsmetrics;
mod wanservice;
mod license;
mod enterpriseprofile;
mod performancemonitor;
mod nexthopaddress;
mod bridgeinterface;
mod vcentercluster;
mod multicastrange;
mod networkmacrogroup;
mod egressaclentrytemplate;
mod patnatpool;
mod applicationbinding;
mod vsgredundantport;
mod multicastlist;
mod trunk;
mod keyservernotification;
mod mirrordestination;
mod natmapentry;
mod domainfipacltemplate;
mod addressmap;
mod underlay;
mod gateway;
mod multinicvport;
mod statistics;
mod nsporttemplate;
mod sshkey;
mod certificate;
mod vcenterdatacenter;
mod customproperty;
mod ltestatistics;
mod l2domaintemplate;
mod vrsredeploymentpolicy;
mod applicationservice;
mod ikegateway;
mod csnatpool;
mod statscollectorinfo;
mod vcenter;
mod bulkstatistics;
mod ingressaclentrytemplate;
mod location;
mod networkperformancebinding;
mod infrastructureaccessprofile;
mod l2domain;
mod ikegatewayconfig;
mod hostinterface;
mod enterprisesecureddata;
mod applicationperformancemanagement;
mod ikecertificate;
mod ingressexternalservicetemplate;
mod me;
mod l7applicationsignature;
mod dhcpoption;
mod keyservermember;
mod nsgateway;
mod nsgatewaytemplate;
mod zonetemplate;
mod nsggroup;
mod siteinfo;
mod alarm;
mod bootstrap;
mod bgpprofile;
mod egressqospolicy;
mod publicnetworkmacro;
mod domainfipacltemplateentry;
mod autodiscovercluster;
mod addressrange;
mod domaintemplate;
mod vm;
mod floatingipacltemplateentry;
mod vmresync;
mod gatewaysecurity;
mod policydecision;
mod applicationperformancemanagementbinding;
mod autodiscovereddatacenter;
mod spatsourcespool;
mod floatingip;
mod egressacltemplate;
mod monitoringport;
mod monitorscope;
mod autodiscoverhypervisorfromcluster;
mod vpnconnection;
mod nsredundantgatewaygroup;
mod application;
mod keyservermonitorsek;
mod ingressadvfwdtemplate;
mod vportmirror;
mod patmapper;
mod psnatpool;
mod bgpneighbor;
mod containerresync;
mod allalarm;
mod enterprise;
mod systemconfig;
mod ikeencryptionprofile;
mod policygrouptemplate;
mod infrastructureconfig;
mod user;
mod tier;
mod policygroup;
mod demarcationservice;
mod nsginfo;
mod firewallrule;
mod nsport;
mod vrsaddressrange;
mod flow;
mod vlantemplate;
mod portmapping;
mod uplinkconnection;
mod globalmetadata;
mod networkperformancemeasurement;
mod ikepsk;
mod ctranslationmap;
mod link;
mod ingressacltemplate;


pub use containerinterface::ContainerInterface;
pub use groupkeyencryptionprofile::GroupKeyEncryptionProfile;
pub use brconnection::BRConnection;
pub use qos::QOS;
pub use ingressadvfwdentrytemplate::IngressAdvFwdEntryTemplate;
pub use bgppeer::BGPPeer;
pub use sharednetworkresource::SharedNetworkResource;
pub use virtualip::VirtualIP;
pub use pspatmap::PSPATMap;
pub use via::Via;
pub use multicastchannelmap::MultiCastChannelMap;
pub use redundancygroup::RedundancyGroup;
pub use tca::TCA;
pub use group::Group;
pub use autodiscoveredgateway::AutoDiscoveredGateway;
pub use zone::Zone;
pub use ikegatewayprofile::IKEGatewayProfile;
pub use ikesubnet::IKESubnet;
pub use infrastructuregatewayprofile::InfrastructureGatewayProfile;
pub use diskstat::DiskStat;
pub use flowsecuritypolicy::FlowSecurityPolicy;
pub use vcentereamconfig::VCenterEAMConfig;
pub use routingpolicy::RoutingPolicy;
pub use enterprisesecurity::EnterpriseSecurity;
pub use vcentervrsconfig::VCenterVRSConfig;
pub use ducgroup::DUCGroup;
pub use nexthop::NextHop;
pub use enterprisenetwork::EnterpriseNetwork;
pub use infrastructurevscprofile::InfrastructureVscProfile;
pub use permission::Permission;
pub use ipreservation::IPReservation;
pub use redirectiontargettemplate::RedirectionTargetTemplate;
pub use subnettemplate::SubnetTemplate;
pub use floatingipacltemplate::FloatingIPACLTemplate;
pub use ikegatewayconnection::IKEGatewayConnection;
pub use redirectiontarget::RedirectionTarget;
pub use firewallacl::FirewallAcl;
pub use patipentry::PATIPEntry;
pub use aggregatemetadata::AggregateMetadata;
pub use networklayout::NetworkLayout;
pub use ingressexternalservicetemplateentry::IngressExternalServiceTemplateEntry;
pub use dscpforwardingclasstable::DSCPForwardingClassTable;
pub use avatar::Avatar;
pub use overlayaddresspool::OverlayAddressPool;
pub use bootstrapactivation::BootstrapActivation;
pub use licensestatus::LicenseStatus;
pub use lteinformation::LTEInformation;
pub use cloudmgmtsystem::CloudMgmtSystem;
pub use vsp::VSP;
pub use domain::Domain;
pub use eventlog::EventLog;
pub use redundantport::RedundantPort;
pub use dscpforwardingclassmapping::DSCPForwardingClassMapping;
pub use porttemplate::PortTemplate;
pub use overlaypatnatentry::OverlayPATNATEntry;
pub use vsc::VSC;
pub use vsd::VSD;
pub use zfbautoassignment::ZFBAutoAssignment;
pub use vport::VPort;
pub use flowforwardingpolicy::FlowForwardingPolicy;
pub use port::Port;
pub use statisticspolicy::StatisticsPolicy;
pub use subnet::Subnet;
pub use container::Container;
pub use ratelimiter::RateLimiter;
pub use keyservermonitorencryptedseed::KeyServerMonitorEncryptedSeed;
pub use gatewaytemplate::GatewayTemplate;
pub use uplinkrd::UplinkRD;
pub use keyservermonitorseed::KeyServerMonitorSeed;
pub use metadata::Metadata;
pub use vrs::VRS;
pub use hsc::HSC;
pub use vlan::VLAN;
pub use ldapconfiguration::LDAPConfiguration;
pub use vsdcomponent::VSDComponent;
pub use zfbrequest::ZFBRequest;
pub use enterprisepermission::EnterprisePermission;
pub use staticroute::StaticRoute;
pub use connectionendpoint::Connectionendpoint;
pub use job::Job;
pub use vminterface::VMInterface;
pub use gatewaysecureddata::GatewaySecuredData;
pub use vcenterhypervisor::VCenterHypervisor;
pub use ptranslationmap::PTranslationMap;
pub use keyservermonitor::KeyServerMonitor;
pub use ducgroupbinding::DUCGroupBinding;
pub use vrsmetrics::VRSMetrics;
pub use wanservice::WANService;
pub use license::License;
pub use enterpriseprofile::EnterpriseProfile;
pub use performancemonitor::PerformanceMonitor;
pub use nexthopaddress::NextHopAddress;
pub use bridgeinterface::BridgeInterface;
pub use vcentercluster::VCenterCluster;
pub use multicastrange::MultiCastRange;
pub use networkmacrogroup::NetworkMacroGroup;
pub use egressaclentrytemplate::EgressACLEntryTemplate;
pub use patnatpool::PATNATPool;
pub use applicationbinding::ApplicationBinding;
pub use vsgredundantport::VsgRedundantPort;
pub use multicastlist::MultiCastList;
pub use trunk::Trunk;
pub use keyservernotification::KeyServerNotification;
pub use mirrordestination::MirrorDestination;
pub use natmapentry::NATMapEntry;
pub use domainfipacltemplate::DomainFIPAclTemplate;
pub use addressmap::AddressMap;
pub use underlay::Underlay;
pub use gateway::Gateway;
pub use multinicvport::MultiNICVPort;
pub use statistics::Statistics;
pub use nsporttemplate::NSPortTemplate;
pub use sshkey::SSHKey;
pub use certificate::Certificate;
pub use vcenterdatacenter::VCenterDataCenter;
pub use customproperty::CustomProperty;
pub use ltestatistics::Ltestatistics;
pub use l2domaintemplate::L2DomainTemplate;
pub use vrsredeploymentpolicy::VRSRedeploymentpolicy;
pub use applicationservice::ApplicationService;
pub use ikegateway::IKEGateway;
pub use csnatpool::CSNATPool;
pub use statscollectorinfo::StatsCollectorInfo;
pub use vcenter::VCenter;
pub use bulkstatistics::BulkStatistics;
pub use ingressaclentrytemplate::IngressACLEntryTemplate;
pub use location::Location;
pub use networkperformancebinding::NetworkPerformanceBinding;
pub use infrastructureaccessprofile::InfrastructureAccessProfile;
pub use l2domain::L2Domain;
pub use ikegatewayconfig::IKEGatewayConfig;
pub use hostinterface::HostInterface;
pub use enterprisesecureddata::EnterpriseSecuredData;
pub use applicationperformancemanagement::Applicationperformancemanagement;
pub use ikecertificate::IKECertificate;
pub use ingressexternalservicetemplate::IngressExternalServiceTemplate;
pub use me::Me;
pub use l7applicationsignature::L7applicationsignature;
pub use dhcpoption::DHCPOption;
pub use keyservermember::KeyServerMember;
pub use nsgateway::NSGateway;
pub use nsgatewaytemplate::NSGatewayTemplate;
pub use zonetemplate::ZoneTemplate;
pub use nsggroup::NSGGroup;
pub use siteinfo::SiteInfo;
pub use alarm::Alarm;
pub use bootstrap::Bootstrap;
pub use bgpprofile::BGPProfile;
pub use egressqospolicy::EgressQOSPolicy;
pub use publicnetworkmacro::PublicNetworkMacro;
pub use domainfipacltemplateentry::DomainFIPAclTemplateEntry;
pub use autodiscovercluster::AutoDiscoverCluster;
pub use addressrange::AddressRange;
pub use domaintemplate::DomainTemplate;
pub use vm::VM;
pub use floatingipacltemplateentry::FloatingIPACLTemplateEntry;
pub use vmresync::VMResync;
pub use gatewaysecurity::GatewaySecurity;
pub use policydecision::PolicyDecision;
pub use applicationperformancemanagementbinding::Applicationperformancemanagementbinding;
pub use autodiscovereddatacenter::Autodiscovereddatacenter;
pub use spatsourcespool::SPATSourcesPool;
pub use floatingip::FloatingIp;
pub use egressacltemplate::EgressACLTemplate;
pub use monitoringport::MonitoringPort;
pub use monitorscope::Monitorscope;
pub use autodiscoverhypervisorfromcluster::AutoDiscoverHypervisorFromCluster;
pub use vpnconnection::VPNConnection;
pub use nsredundantgatewaygroup::NSRedundantGatewayGroup;
pub use application::Application;
pub use keyservermonitorsek::KeyServerMonitorSEK;
pub use ingressadvfwdtemplate::IngressAdvFwdTemplate;
pub use vportmirror::VPortMirror;
pub use patmapper::PATMapper;
pub use psnatpool::PSNATPool;
pub use bgpneighbor::BGPNeighbor;
pub use containerresync::ContainerResync;
pub use allalarm::AllAlarm;
pub use enterprise::Enterprise;
pub use systemconfig::SystemConfig;
pub use ikeencryptionprofile::IKEEncryptionprofile;
pub use policygrouptemplate::PolicyGroupTemplate;
pub use infrastructureconfig::InfrastructureConfig;
pub use user::User;
pub use tier::Tier;
pub use policygroup::PolicyGroup;
pub use demarcationservice::DemarcationService;
pub use nsginfo::NSGInfo;
pub use firewallrule::FirewallRule;
pub use nsport::NSPort;
pub use vrsaddressrange::VRSAddressRange;
pub use flow::Flow;
pub use vlantemplate::VLANTemplate;
pub use portmapping::PortMapping;
pub use uplinkconnection::UplinkConnection;
pub use globalmetadata::GlobalMetadata;
pub use networkperformancemeasurement::NetworkPerformanceMeasurement;
pub use ikepsk::IKEPSK;
pub use ctranslationmap::CTranslationMap;
pub use link::Link;
pub use ingressacltemplate::IngressACLTemplate;